name: Deploy

on:
  # mainブランチにpushしたとき動く
  push:
    branches: [main]

env:
  REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
  REACT_APP_APP_ID: ${{ secrets.REACT_APP_APP_ID }}
  REACT_APP_MEASUREMENT_ID: ${{ secrets.REACT_APP_MEASUREMENT_ID }}
  REACT_APP_PROJECT_ID: ${{ secrets.REACT_APP_PROJECT_ID }}
  REACT_APP_SENDER_ID: ${{ secrets.REACT_APP_SENDER_ID }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # ビルドキャッシュ設定です。デプロイの動作自体には必要ないので消してしまっても大丈夫です。
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      # yarn installを実行します
      - name: Install
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      # yarn buildを実行します (production用のコマンドが異なる場合はcmdの部分を書き換えてください)
      - name: Build
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build
      # ビルドした成果物を保存します。ビルド結果のパスがbuildではない場合は書き換えてください
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: build
